config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  get "profile", to: "pages#profile"
  resources :movies, only: [:show, :index]
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: :create
  end
  resources :lists, only: :show do
    member do
      post 'toggle_favorite', to: "lists#toggle_favorite"
    end
    resources :movies, only: [:index, :show] do
      member do
        post 'toggle_favorite', to: "movies#toggle_favorite"
      end
    end
  end
  resources :bookmarks, only: :destroy
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list" }
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true, presence: true
  acts_as_favoritable
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
  acts_as_favoritable
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :list
  validates :comment, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :lists
         acts_as_favoritor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!, only: [:toggle_favorite, :create, :destroy]

  def toggle_favorite
    @list = List.find_by(id: params[:id])
    current_user.favorited?(@list)  ?current_user.unfavorite(@list) : current_user.favorite(@list)
  end

  def index
    @lists = List.all

  end

  def show

    @list = List.find(params[:id])
    @user = @list.user
    @username = @user.username
    @bookmark = Bookmark.new
    @review = Review.new(list: @list)
  end

  def new
   @list = List.new
  end

  def create

    @list = List.new(list_params)
    @list.user_id = current_user.id
    if @list.save
        redirect_to list_path(@list)
      else
        render :new
      end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: :toggle_favorite

  def toggle_favorite
    @movie = Movie.find_by(id: params[:id])
    current_user.favorited?(@movie)  ?current_user.unfavorite(@movie) : current_user.favorite(@movie)
  end


  def index
    @movies = Movie.all
    @favorite_movies = current_user.favorited_by_type('Movie')
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end


  def create
    @movie = Movie.new(movie_params)
    @movie.save
    redirect_to movie_path(@movie)
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url)
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(movie_params)

    # no need for app/views/restaurants/update.html.erb
    redirect_to movie_path(@movie)
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to restaurants_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def profile
    @user = current_user
    @favorite_movies = current_user.favorited_by_type('Movie')
    @favorite_lists = current_user.favorited_by_type('List')

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_list
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def create

    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end

  def destroy

    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.label :Comment %>
  <%= f.input :comment, label: false %>
  <%= f.label :Movie %>
  <%= f.association :movie, label: false %>
  <%= f.submit class: 'btn btn-success rounded-pill mt-3' %>
<% end %>

app/views/bookmarks/_new.html.erb
  <div class="modal fade" id="new_movie_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Add a movie to your <%= list.name %> list</h5>
          <button type="submit" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= simple_form_for [@list, @bookmark] do |f| %>
            <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Select a movie", input_html: { data: { controller: "slect2" } } %>
            <%= f.input :comment, placeholder: "Enter a comment about the movie" %>

        <div class="modal-footer">
            <%= f.submit "Add movie", class: "btn btn-flat", method: :post, remote:true  %>
          <% end %>
          <button type="button" class="btn btn-cancel" data-bs-dismiss="modal">Back</button>
        </div>
        </div>
      </div>
    </div>
  </div>

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your <%= @list.name %> list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
          <%= f.association :movie, prompt: 'Select a movie', input_html: { data: { controller: 'select2' } } %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>

      <%= yield %>
      <script src="search.js"></script>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@lists) do |f| %>
  <%= f.input :name %>
  <%= f.submit class: 'btn btn-success mt-3' %>
  <%= f.button :button, 'Back', type: :back, class: 'btn btn-danger mt-3' %>
<% end %>

app/views/lists/_header.html.erb
<div class="banner-container banner-change">
  <div class="banner-nav-bar">
    <div><h1><i class="fas fa-play"></i>My Movies Lists</h1>
        <p class="text-center" style="margin-top: 10px;">Exercise created during the Bootcamp at Le wagon Lisbon.</p>
    </div>
  </div>
</div>

app/views/lists/_like_button.html.erb
<div class="like-icon mx-2 <%= 'red' if current_user.favorited?(list) %>" data-id="<%= list.id %>">
  <i class="fas fa-heart"></i>
</div>

app/views/lists/_list.html.erb
<div class="list" data-id="<%= list.id %>">
  <h3><%= list.name %></h3>
  <p><%= list.name %></p>
</div>

app/views/lists/edit.html.erb
<div class="container">

  <div class="">
    <div class="row align-items-start">
    <div class="col-lg-6" >
    <h1>Edit List</h1>
    <br>
      <%= render 'form', list: @lists %>
   </div>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="d-flex align-items-center justify-content-center mt-40px">

  <%= link_to "Create a movie list", new_list_path, class: "btn btn-flat" %>
</div>



          <!-- BEGIN TABLE RESULT -->
      <div class="container">
        <div class="row">
          <div class="col-md-12 fontes">
            <div class="grid search  p-3 ">
              <div class="grid-body">
                <div class="row">
                  <div class="col-md-8">
                    <%= simple_form_for :search, url: lists_path, method: :get do |f| %>
                      <div class="input-group mb-3">
                        <%= text_field_tag :query, params[:query], style: "border-radius: 5px;", class: "form-control", placeholder: "Search" %>
                        <button class="btn-primary ms-1" style="width: 50px; border-radius: 5px; background-color: #7e2bb6; border-color: hsl(277, 76%, 3%);" type="submit"><i class="text-light fa fa-search"></i></button>
                      </div>
                    <% end %>



                    <div class="table-responsive">
                      <ul class="responsive-table">
                        <li class="table-header">
                          <div class="col col-1 fontes">User</div>
                          <div class="col col-2 fontes">List Name</div>
                          <div class="col col-3 fontes">Users favorite</div>
                        </li>

                        <% @lists.each do |list| %>
                          <%= link_to list_path(list) do %>
                            <li class="table-row d-flex">
                              <div class="avatar-bordered col col-1"><img src="https://kitt.lewagon.com/placeholder/users/ssaunier" alt=""></div>
                              <div class="col col-2 product"><strong><%= list.name %></strong></div>
                              <div class="col col-3 fs-6 text-center cor" data-label="Amount"><%= list.favoritors.count %></div>
                            </li>
                          <% end %>
                        <% end %>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
        <!-- END TABLE RESULT -->

            <!-- BEGIN PAGINATION -->
            <div class="container">
              <ul class="pagination responsive-table ps-4 mt-1">
                <li class="disabled"><a href="#"  style="color: #7e2bb6;">«</a></li>
                <li class="active"><a href="#"  style="color: #7e2bb6;">1</a></li>
                <li><a href="#"  style="color: #7e2bb6;">2</a></li>
                <li><a href="#"  style="color: #7e2bb6;">3</a></li>
                <li><a href="#"  style="color: #7e2bb6;">4</a></li>
                <li><a href="#"  style="color: #7e2bb6;">5</a></li>
                <li><a href="#"  style="color: #7e2bb6;">»</a></li>
              </ul>
            </div>
            <!-- END PAGINATION -->
          </div>
          <!-- END RESULT -->
        </div>
      </div>
    </div>
  </div>
  <!-- END SEARCH RESULT -->
</div>
</div>

app/views/lists/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'List Title' %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<%= render "bookmarks/new", list: @list %>
<div class="position-relative">

    <h1><%= @list.name %></h1>
  </div>
    <span class="movie-tag"><%= pluralize(@list.movies.size, 'movie') %></span>
</div>
<div class="container mb-5">
  <div class="d-flex justify-content-between my-4">
    <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't saved any movies yet!" if @list.movies.empty? %></em></small></span>
    <div>
      <button type="button" class="btn btn-flat" data-bs-toggle="modal" data-bs-target="#new_movie_modal">
        add a movie
      </button>
      <%= link_to "delete this list", list_path(@list), method: :delete, class: "btn btn-cancel", data: { confirm: "Are you sure you want to delete this list?" } %>
    </div>
    <%= link_to "Add list to favorites", toggle_favorite_list_path(@list), remote: true, method: :post %>
  </div>
  <div class="relative">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <%= link_to movie_path(movie), class: "text-decoration-none" do %>
        <div class="col-8 card-product  d-flex flex-row  data-aos="zoom-in">
          <div class="card-product img" >
            <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
          </div>

          <div class="p-3 rounded-bottom ">
            <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i><br>

            <small class="text-muted"><%= movie.overview %></small>
            <div class="d-flex align-items-center justify-content-between pt-4">
              <div>
                </span></strong><%= link_to "add", toggle_favorite_list_movie_path(movie), remote: true, method: :post %>
              </div>
                <% if @list.user = current_user %>
                  <small class="text-right flex-shrink-0"><%= link_to "delete", bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %></small>
                <% end %>
              </div>

          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <hr class="my-5">
  <div class="row">
    <div class="col-12 col-sm-6">
      <h3>Reviews</h3>
      <% if @list.reviews.empty? %>
        <small><em class="text-muted">Be the first one to review this list</em></small>
      <% end %>
      <% @list.reviews.each do |review| %>
        <div>
          <% review.rating.times do %>
            <i class="fas fa-star star-yellow"></i>
          <% end %>
          <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
          <p class="mb-0"><%= review.comment %></p>
        </div>
        <hr>
      <% end %>
    </div>
    <div class="col-12 col-sm-6">
      <div class="bg-white rounded p-3">
        <h5>Add your review</h5>
        <%= simple_form_for [@list, @review] do |f| %>
          <%= f.input :comment, placeholder: "Add your review here..." %>
          <%= f.input :rating, as: :select, collection: (1..5), required: true, prompt: "What's your rating", input_html: { data: { controller: "jquery-bar-rating" } } %>
          <%= f.submit class:"btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/toggle_favorite.js.erb
var listId = '<%= @list.id%>'
function toggleLikeButton(listId, innerHTML) {
  let likeButton = document.querySelector('.like-icon[data-id="${listId}"]')
  likeButton.classList.toggle('red');
}
toggleLikeButton(listId);

app/views/movies/_like_button.html.erb
<div class="like-icon mx-2 <%= 'red' if current_user.favorited?(movie) %>" data-id="<%= movie.id %>">
  <i class="fas fa-heart"></i>
</div>

app/views/movies/_movie.html.erb
<div class="movie" data-id="<%= movie.id %>">
  <h3><%= movie.title %></h3>
  <p><%= movie.overview %></p>
</div>

app/views/movies/index.html.erb
<form id="form">
  <div class="movie">
    <img src="" alt="">
    <div class="movie-info">
      <h3>Movie Title</h3>
      <span>9.7</span>
    </div>

    <div class="overview">
      <h3>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus harum alias unde inventore, consequuntur ullam eum, blanditiis laboriosam, minima eos similique. Velit nihil debitis, consequuntur harum praesentium laboriosam sequi distinctio.
      </h3>
    </div>
  </div>

</form>

app/views/movies/show.html.erb
<h1 class="p-3 text-center fw-bold main-title"></h1>

      <div class="container" style="margin-top:10px; width: 50rem;">
        <div class="row">
            <div class="col-md-3 gx-0">
                <div class="card-sl" style="width: 50rem; height: 28rem">

                    <div class="">
                      <div class="flat-card-map col-12 mx-auto">
                       <div class="card-product img" >
                        <%= @movie.poster_url %>
                       </div>
                      </div>
                    </div>

                    <div class="card-heading">
                        <%= @movie.title %>
                    </div>

                    <div class="card-text">
                        <%= @movie.overview %>
                    </div>
                   <div class="card-text">

                    <%= link_to "Add to Watch List ",  toggle_favorite_list_movie_path(@movie), remote: true, method: :post %>

                </div>
                </div>
            </div>
        </div>
      </div>

<h1 class="p-3 text-center fw-bold main-title"></h1>

      <div class="container" style="margin-top:10px; width: 50rem;">
        <div class="row">
            <div class="col-md-3 gx-0">
                <div class="card-sl" style="width: 50rem; height: 28rem">

                <%= @movie.poster_url %>

                    <div class="card-heading">
                        <%= @movie.title %>

                    <div class="card-text">
                        <%= @movie.overview %>
                    </div>
                   <div class="card-text">
                        <%= @movie.rating %>
                    </div>

                      <%= link_to "Add to Watch List ",  toggle_favorite_list_movie_path(@movie), remote: true, method: :post %>

                </div>
            </div>
        </div>
      </div>

        <div class="flat-show-card text-center mt-5">
          <div class="flex-align">
            <h6 class="no-mb">Share with your friends</h6>

          <div class="flex">
              <i class="fa fa-brands fa-facebook-square fa-2x me-2" style="color:#7e2bb6;"></i>
              <i class="fa fa-brands fa-twitter-square fa-2x me-2" style="color:#7e2bb6;"></i>
              <i class="fa fa-brands fa-pinterest-square fa-2x me-2" style="color:#7e2bb6;"></i>
              <i class="fa fa-envelope-square fa-2x" style="color:#7e2bb6;"></i>
            </div>

          </div>
        </div>

app/views/movies/toggle_favorite.js.erb
var movieId = '<%= @movie.id%>'
function toggleLikeButton(movieId, innerHTML) {
  let likeButton = document.querySelector('.like-icon[data-id="${movieId}"]')
  likeButton.classList.toggle('red');
}
toggleLikeButton(movieId);

app/views/pages/profile.html.erb
<h1 class="p-3 text-center fw-bold main-title fontes">Username</h1>

<!-- My bookings Container -->
<div class="row gx-0 fontes">
  <div class="container p-3 rounded " style="width: 90rem;">


    <!-- Board Lateral direito WALLET-->

    <div class="container p-3 bg-light border rounded " style="height: 100%; width: 27rem; float:right;">
      <div class="col-md-12 text-center">
        <h3 class="fw-bold border-bottom main-title">Username Lists</h3>



        <!-- Board Lateral direito WALLET-->
        <!-- Board Lateral direito list services-->
        <div class="col-md-12 text-center">

          <table class="table align-middle mt-3 bg-white main-title border-top: 2px solid currentColor;">
            <thead class="table-header text-light">
              <tr>
                <th class = "fontes" >My Services </th>
              </tr>
            </thead>
          </table>

          <%= link_to '+ Add List ' , new_list_path, class: "btn btn-outline-success rounded-pill border" %>

            <div class="container d-flex justify-content-center fontes" style="margin-left:-17px;">
            </div>
        </div>

        <div class="container d-flex justify-content-center fontes" style="margin-left:-17px;">
          <ul class="listservice-group text-white col-md-12 main-title">
            <% @user.lists.each do |list| %>
              <%= link_to list_path(list) do %>
                <li class="listservice-group-item d-flex justify-content-between align-content-center">

                  <div class="d-flex flex-row">

                    <div class="about">
                      <h6 class="mt-2 fontes">
                        <%= list.name %>
                      </h6>
                      <div class="about d-flex">
                        <span class="ms-1">
                          <%= list.name %>
                        </span>
                        <div >
                          <strong><span style="float:right;"><%= list.name %></span></strong>
                        </div>
                      </div>
                    </div>
                  </div>

                </li>
                <% end %>
                  <% end %>
          </ul>
        </div>

        <!-- final Board Lateral direito list services-->

        <div class="row mt-3 gx-0 fontes">
        </div>
      </div>
    </div>

    <!-- Final Board Lateral direito-->

    <!-- Board Lateral esquerdo -->

    <div class="container p-3 bg-light border rounded fontes" style="width: 60rem; float:left; height: 100%;">
      <div class="col-md-12">
        <h3 class="fw-bold border-bottom main-title text-center fontes"> Watch List</h3>

        <table class="table align-middle mt-3 bg-white main-title fontes">
        <thead class="table-header ">
          <tr>
            <th>Poster</th>
            <th>Title</th>
            <th>Overview</th>
            <th>Rating</th>
            <th class="text-center">Lists
            <th class="text-center">Remove</th>
          </th>
        </thead>

       <tbody>
        <% @favorite_movies.each do |movie| %>

            <tr style="height: 67px">
              <td>
                <p class="fw-bold mb-1 fontes">
                  <%= movie.poster_url %>
                </p>
              </td>

              <td>
                <p class="fw-normal mb-1 fontes">
                  <%= movie.title %>
                </p>
              </td>

              <td>
                <p class="fw-normal mb-1 fontes">
                  <%= movie.overview %>
                </p>
              </td>

              <td>
                <p class="fw-normal mb-1 fontes">
                <%= movie.rating %>
                </p>
              </td>

            </tr>
            <% end %>
        </tbody>
        </table>

      </div>
    </div>



      <!-- Final Board Lateral esquerdo -->

    </div>
  </div>
</div>

<!-- My Services were booked Container -->



<div class="row gx-0">
  <div class="container p-3 rounded " style="width: 90rem; height: 20rem;">




   <div class="container bg-light border rounded " style="height: 100%; width: 27rem; float:right;">
      <div class="col-md-12 text-center">
        <h3 class="fw-bold border-bottom main-title mt-3">History</h3>

        <table class="table align-middle mt-3 bg-white main-title border-top: 2px solid currentColor;">
          <thead class="table-header text-light">
            <tr>
              <th>Title</th>
              <th class="text-end">Date</th>
              <th class="text-end">Balance</th>
            </tr>
          </thead>
        </table>




      </div>
    </div>





    <div class="container bg-light border rounded " style="height: 100%; width: 60rem; float:left;">
      <h3 class="fw-bold border-bottom main-title mt-3 text-center">Favorite lists</h3>
      <table class="table align-middle mt-3 bg-white main-title">
        <thead class="table-header text-light">
          <tr>
            <th>User</th>
            <th>List Name</th>
            <th>List Description</th>
            <th>Favorites</th>
            <th class="text-center">Remove</th>


        </thead>
        <tbody>
        <% @favorite_lists.each do |list| %>

            <tr style="height: 67px">
              <td>
                    <p class="fw-bold mb-1 fontes">
                      <%= list.user %>
                    </p>
              </td>

              <td>
                <p class="fw-normal mb-1 fontes">
                <%= list.name %>
                </p>
              </td>

              <td>
                <p class="fw-normal mb-1 fontes">
                <%= list.name %>
                </p>
              </td>

              <td>
                <p class="fw-normal mb-1 fontes">
                <%= list.name %>
                </p>
              </td>





            </tr>
            <% end %>
        </tbody>
        </table>



    </div>
  </div>
</div>
</div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon color">
  <div class="container-fluid logo">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "icon.png" %>

    <% end %>
    <h1> Watch List </h1>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to 'notifications', "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item ">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>